## 회귀 예측(Regression)

- 데이터
- 모델
- 평가

### 데이터 관련

In [6]:
from sklearn import datasets
diabetes_X,diabetes_y = datasets.load_diabetes(return_X_y= True)

In [26]:
type(diabetes_X),type(diabetes_y),diabetes_X.shape,diabetes_y.shape

(numpy.ndarray, numpy.ndarray, (442, 10), (442,))

### 모델

In [7]:
from sklearn import linear_model    # 선형모델


In [12]:
linearRegression = linear_model.LinearRegression() # 학습 장소 선택

In [14]:
linearRegression.fit(diabetes_X,diabetes_y) # 학습 진행

LinearRegression()

### 평가

In [16]:
diabetes_X[:2],diabetes_y[:2]

(array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
         -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, -0.02632753, -0.00844872,
         -0.01916334,  0.07441156, -0.03949338, -0.06833155, -0.09220405]]),
 array([151.,  75.]))

In [15]:
linearRegression.predict(diabetes_X[:2])

array([206.11667725,  68.07103297])

### 학습 공식 확인

In [19]:
linearRegression.coef_,linearRegression.coef_.shape,linearRegression.intercept_

(array([ -10.0098663 , -239.81564367,  519.84592005,  324.3846455 ,
        -792.17563855,  476.73902101,  101.04326794,  177.06323767,
         751.27369956,   67.62669218]),
 (10,),
 152.13348416289597)

In [18]:
diabetes_X[:1]

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613]])

In [25]:
(linearRegression.coef_ * diabetes_X[:1]).sum() + linearRegression.intercept_

206.11667724510562