In [11]:
import pandas as pd
df_seoul120 = pd.read_csv("https://bit.ly/seoul-120-text-csv")
df_seoul120

번호      분류                                            제목  \
0     2645      복지                                   아빠 육아휴직 장려금   
1     2644      경제                             [서울산업진흥원] 서울메이드란?   
2     2643      환경                                     (강북구) 정비중   
3     2642      복지                   광진맘택시 운영(임산부,영아 양육가정 전용 택시)   
4     2641      복지                                마포 뇌병변장애인 비전센터   
...    ...     ...                                           ...   
2640     5  주택도시계획  이미 지정된 재정비촉진지구의 인접지를 추가 확장하고 싶은데 어떻게 해야 하나요?   
2641     4      환경                                  수돗물의 톤당 원가는?   
2642     3      복지            출산휴가후 집근처에 안심하고 맡길 수 있는 어린이집이 있는지?   
2643     2      교통                 자동차검사장을 지정받고자 하는데 어떻게 해야 하나요?   
2644     1      환경                         폐기대상 문서의 폐기는 어떻게 하나요?   

                                                     내용      내용번호  
0     아빠 육아휴직 장려금   업무개요  남성근로자의 육아휴직을 장려하고 양육에 따른 경...  23522464  
1     서울산업진흥원 서울메이드란 서울의 감성을 담은 다양하고 새로운 경험을 제공하기 위해...  23194045  
2     강북구 정비중  업무개요  투명 폐트병을 교환보상하므로 수거율을 높이고 폐기물을 감...  23032485  
3     광진맘택시 운영임산부영아 양육가정 전용 택시  업무개요 교통약자인 임산부와 영아가정...  22904492  
4     마포 뇌병변장애인 비전센터 마포뇌병변장애인 비전센터 운영   구분 내용  목적  학...  22477798  
...                                                 ...       ...  
2640  이미 지정된 재정비촉진지구의 인접지를 추가 확장하고 싶은데 어떻게 해야 하나요 관할...   2894353  
2641  수돗물의 톤당 원가는우리시 년 톤당 원가는 원 입니다 우리시 년 톤당 요금은 원 입니다   19353862  
2642  출산휴가후 집근처에 안심하고 맡길 수 있는 어린이집이 있는지   서울시 육아종합지원...  19699584  
2643  자동차검사장을 지정받고자 하는데 어떻게 해야 하나요  자동차종합정비업체 소형자동차정...   2898293  
2644  폐기대상 문서의 폐기는 어떻게 하나요보존기간이 경과된 문서의 폐기는 정보공개정책과로...  19431143  

[2645 rows x 5 columns]

In [12]:
import pandas as pd
import pyLDAvis
import pyLDAvis.lda_model
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation

## 자연어 전처리

In [13]:
stopwords = []

In [14]:
# 토크나이징 함수 정의
from konlpy.tag import Okt
okt = Okt()
def Tokenizer(raw, pos=["Noun","Verb","Modifier","Adjective"], stopword=stopwords):
    return [
        word for word, tag in okt.pos(
            raw, 
            norm=True,   # normalize 그랰ㅋㅏ -> 그래ㅋㅋ
            stem=True    # stemming 바뀌나->바뀌다
            )
            if len(word) > 1 and tag in pos and word not in stopword

    ]

In [15]:
# tokenizing
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfVectorizer = TfidfVectorizer(tokenizer = Tokenizer,max_df=0.95,min_df=2)

In [16]:
features = tfidfVectorizer.fit_transform(df_seoul120["내용"])
features.toarray()[:2]

/usr/local/lib/python3.11/site-packages/sklearn/feature_extraction/text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
import numpy as np 
np.where(features.toarray()[:1] > 0 )

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([  69,   76,  217,  220,  341,  362,  382,  392,  415,  471,  770,
         774,  790,  914,  961,  966, 1033, 1137, 1172, 1436, 1446, 1664,
        1666, 1710, 1729, 1903, 1998, 2197, 2211, 2277, 2291, 2297, 2384,
        2492, 2538, 2579, 2608, 2685, 2906, 3084, 3103, 3132, 3133, 3285,
        3746, 3850, 3952, 3959, 4020, 4238, 4264, 4537, 4584, 4674, 4692,
        4706, 4766, 4837, 4876, 4960, 4975, 4991, 5057, 5093, 5291, 5386,
        5522, 5569, 5616, 5617, 5760, 5820, 5821, 6154, 6436, 6613, 6698,
        6971, 7027]))

In [25]:
latentDirichletAllocation_5=LatentDirichletAllocation(n_components=5,n_jobs=-1)

In [26]:
latentDirichletAllocation_5.fit(features)

LatentDirichletAllocation(n_components=5, n_jobs=-1)

In [28]:
vis_5 = pyLDAvis.lda_model.prepare(latentDirichletAllocation_5,features,tfidfVectorizer)
vis_5

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic                                                
3     -0.109873 -0.057688       1        1  67.467952
0     -0.060348  0.082107       2        1  16.592934
4      0.057968 -0.010867       3        1   7.036295
1      0.057504 -0.004135       4        1   4.686280
2      0.054749 -0.009418       5        1   4.216539, topic_info=     Term        Freq       Total Category  logprob  loglift
1593   돋다   65.000000   65.000000  Default  30.0000  30.0000
6698   하다  135.000000  135.000000  Default  29.0000  29.0000
291   건축물   19.000000   19.000000  Default  28.0000  28.0000
532   공무원   15.000000   15.000000  Default  27.0000  27.0000
290    건축   20.000000   20.000000  Default  26.0000  26.0000
...   ...         ...         ...      ...      ...      ...
4294   요건    0.403645    4.664736   Topic5  -7.1482   0.7189
4676   이다    0.488553   33.863794   Topic5  -6.9573  -1.0725
915    근무    0.399376    7.363645   Topic5  -7.1588   0.2517
1666  되어다    0.402914   20.319590   Topic5  -7.1500  -0.7545
3194   설치    0.401525   22.661330   Topic5  -7.1534  -0.8670

[297 rows x 6 columns], token_table=      Topic      Freq  Term
term                       
135       1  0.613163    감사
135       2  0.367898    감사
135       4  0.122633    감사
148       2  0.733241  감정평가
177       1  0.384574    강의
...     ...       ...   ...
7022      1  0.936962    확인
7022      2  0.052053    확인
7078      1  0.272040    회의
7078      2  0.544079    회의
7078      3  0.136020    회의

[321 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[4, 1, 5, 2, 3])

In [29]:
pyLDAvis.enable_notebook()
components_5_display = pyLDAvis.display(vis_5)
components_5_display

### components : 3

In [30]:
latentDirichletAllocation_3=LatentDirichletAllocation(n_components=3,n_jobs=-1)

In [31]:
latentDirichletAllocation_3.fit(features)

LatentDirichletAllocation(n_components=3, n_jobs=-1)

In [60]:
vis_3 = pyLDAvis.lda_model.prepare(latentDirichletAllocation_3,features,tfidfVectorizer)

### components : 5

In [38]:
latentDirichletAllocation_5=LatentDirichletAllocation(n_components=5,n_jobs=-1)

In [39]:
latentDirichletAllocation_5.fit(features)

LatentDirichletAllocation(n_components=5, n_jobs=-1)

In [61]:
vis_5 = pyLDAvis.lda_model.prepare(latentDirichletAllocation_5,features,tfidfVectorizer)

### components : 7

In [34]:
latentDirichletAllocation_7=LatentDirichletAllocation(n_components=7,n_jobs=-1)

In [35]:
latentDirichletAllocation_7.fit(features)

LatentDirichletAllocation(n_components=7, n_jobs=-1)

In [62]:
vis_7 = pyLDAvis.lda_model.prepare(latentDirichletAllocation_7,features,tfidfVectorizer)

### components 별 비교

In [57]:
pyLDAvis.enable_notebook
pyLDAvis.display(vis_3)

In [58]:
pyLDAvis.enable_notebook
pyLDAvis.display(vis_5)

In [59]:
pyLDAvis.enable_notebook()
pyLDAvis.display(vis_7)